version: '3.7'

services:
  app:
    build:
      dockerfile: dockerfile
    environment:
      MODULE_NAME: "main"
      MAX_WORKERS: 2
    ports:
      - "${APP_PORT}:80"
    env_file:
      - .env
